name: sanchalak
description: "Sanchalak is a comprehensive train travel app offering real-time tracking, secure access, and user-friendly features for railway staff, contractors, and passengers."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.1
  provider: ^6.1.2
  open_app_settings: ^2.0.1
  collection: ^1.18.0
  universal_html: ^2.2.4
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  open_filex: ^4.4.0
  downloads_path_provider_28: ^0.1.2
  pinput: ^5.0.0
  cloud_firestore: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/Verified.gif
    - assets/images/google.png
    - assets/images/verified.png

  uses-material-design: true


